apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: mungta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: mungtaregistry.azurecr.io/mungta/dev/question-service

---
apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: question-service