apiVersion: apps/v1
kind: Deployment
metadata:
  name: question
  namespace: mungta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
        - name: question
          image: mungtaregistry.azurecr.io/mungta/dev/question

---
apiVersion: v1
kind: Service
metadata:
  name: question
  namespace: mungta
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: question