spring:
  datasource:
    jdbc-url: jdbc:mysql://${DB_HOST}:3306/question_dev?serverTimezone=Asia/Seoul&validationQuery="select 1"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: munta-question
  jpa:
#    hibernate:
#      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
#    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 'classpath:db/migration'
    baseline-version: 0

server:
  port: 8080

logging:
  config: classpath:logging/logback-mungta-prod.xml
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true